name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
  schedule:
    # At minute 0 past hour 6. (see https://crontab.guru)
    - cron: "00 06 * * *"

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit).
  group: ci-build-test-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  # this actually turns build isolation on!
  # pip flags -> env variables conversion is weird...
  PIP_NO_BUILD_ISOLATION: false

jobs:
  # format:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run clang-format style check for C/C++/Protobuf programs.
  #       uses: jidicula/clang-format-action@v4.16.0

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [
            ubuntu-22.04,
            # ubuntu-22.04-arm,
            macos-15,
          ]
        py_version: ["3.13"]
        # py_version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v6
        with:
          version: "1.12.1"

      - name: set ENV macos
        if: contains(matrix.os, 'macos')
        shell: bash
        run: |
          # error: 'value' is unavailable: introduced in macOS 10.13
          echo "MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion)" | tee -a $GITHUB_ENV

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "${{ matrix.py_version }}"

      - name: Install dependencies
        run: |
          cat >> pyproject.toml << 'EOF'
          required-environments = [
              "sys_platform == 'linux' and platform_machine == 'x86_64'",
              "sys_platform == 'darwin' and platform_machine == 'arm64'",
          ]
          EOF
          uv sync

      - name: Configure CMake
        run: >-
          uv run cmake -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_PREFIX_PATH=$(uv run python -m mlir_wheel --root-dir)
          -DLLVM_EXTERNAL_LIT=$(uv run which lit)
          -DPython3_EXECUTABLE=$(uv run which python)
          -DENABLE_HERBIE=OFF
          -B build
          -S $PWD

      - name: Build and test with CMake/lit
        run: |
          uv run cmake --build build --target check-tamagoyaki
